# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
from raydriver.grbl import types
import typing
from . import grbl
__all__ = [
    "alarm_code_to_device_error",
    "detect_unit_system_from_settings",
    "error_code_to_device_error",
    "extract_device_name",
    "extract_device_name_from_output",
    "gcode_to_p_number",
    "grbl",
    "is_grbl_output",
    "is_report_in_inches",
    "parse_grbl_parser_state",
    "parse_grbl_settings",
    "parse_msg",
    "parse_opt_info",
    "parse_probe_line",
    "parse_setting_pairs",
    "parse_state",
    "parse_ver",
    "parse_version",
    "parse_wcs_line",
    "split_realtime_commands",
    "strip_gcode_comments",
    "version_supports_single_axis_homing",
]

def alarm_code_to_device_error(alarm_code: builtins.str) -> types.DeviceError:
    r"""
    Look up an alarm code in the GRBL alarm table.
    """

def detect_unit_system_from_settings(settings_lines: typing.Sequence[builtins.str]) -> typing.Optional[builtins.str]:
    r"""
    Infer the unit system ("metric"/"imperial") from `$$` lines.
    """

def error_code_to_device_error(error_code: builtins.str) -> types.DeviceError:
    r"""
    Look up an error code in the GRBL error table.
    """

def extract_device_name(build_info: typing.Sequence[builtins.str]) -> builtins.str:
    r"""
    Extract a human-readable device name from build info lines.
    """

def extract_device_name_from_output(data: typing.Sequence[builtins.int]) -> typing.Optional[builtins.str]:
    r"""
    Extract a device name from raw serial output, falling back to
    the first informative banner line.
    """

def gcode_to_p_number(wcs_slot: builtins.str) -> typing.Optional[builtins.int]:
    r"""
    Convert a G-code WCS name (e.g. "G54") to its P-number.
    """

def is_grbl_output(data: typing.Sequence[builtins.int]) -> builtins.bool:
    r"""
    True when raw serial output identifies a Grbl device.
    """

def is_report_in_inches(settings_lines: typing.Sequence[builtins.str]) -> builtins.bool:
    r"""
    True when the `$13` (Report in inches) flag is set.
    """

def parse_grbl_parser_state(response_lines: typing.Sequence[builtins.str]) -> typing.Optional[builtins.str]:
    r"""
    Parse `$G` response lines to find the active WCS (G54-G59).
    """

def parse_grbl_settings(lines: typing.Sequence[builtins.str]) -> builtins.dict[builtins.str, builtins.float]:
    r"""
    Parse `$$` lines into `{key: value}` floats.
    """

def parse_msg(line: builtins.str) -> typing.Optional[tuple[builtins.str, builtins.str]]:
    r"""
    Parse a `[MSG:key:value]` line into `(key, value)`.
    """

def parse_opt_info(line: builtins.str) -> typing.Optional[builtins.int]:
    r"""
    Extract the RX buffer size from an `[OPT:...]` line.
    """

def parse_probe_line(line: builtins.str) -> typing.Optional[tuple[tuple[builtins.float, builtins.float, builtins.float], builtins.bool]]:
    r"""
    Parse a `[PRB:x,y,z:success]` line into `(pos, success)`.
    """

def parse_setting_pairs(lines: typing.Sequence[builtins.str]) -> builtins.list[tuple[builtins.str, builtins.str]]:
    r"""
    Parse `$$` lines into ordered `(key, raw_value)` pairs.
    """

def parse_state(state_str: builtins.str, default: typing.Optional[types.DeviceState] = None, report_in_inches: builtins.bool = False) -> types.DeviceState:
    r"""
    Parse a GRBL status string like `<Idle|MPos:10,20,30>` into a
    DeviceState, using *default* as the base.  When
    *report_in_inches* is true, positions are converted back to mm.
    """

def parse_ver(line: builtins.str) -> typing.Optional[tuple[builtins.str, typing.Optional[builtins.str]]]:
    r"""
    Parse a `[VER:...]` line into `(version, build_name)`.
    """

def parse_version(response_lines: typing.Sequence[builtins.str]) -> typing.Optional[builtins.str]:
    r"""
    Parse `$I` response lines to extract the firmware version.
    """

def parse_wcs_line(line: builtins.str) -> typing.Optional[tuple[builtins.str, tuple[builtins.float, builtins.float, builtins.float]]]:
    r"""
    Parse a `[G5x:x,y,z]` line from `$#` output.
    """

def split_realtime_commands(lines: typing.Sequence[builtins.str]) -> tuple[builtins.list[builtins.str], builtins.list[builtins.str]]:
    r"""
    Split command lines into `(gcode, realtime)` groups.
    """

def strip_gcode_comments(line: builtins.str) -> builtins.str:
    r"""
    Strip G-code comments from a line.
    """

def version_supports_single_axis_homing(version_num: builtins.float, version_letter: builtins.str = '') -> builtins.bool:
    r"""
    True if a GRBL version supports single-axis homing (> 1.1 or
    1.1g and newer).
    """

