# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
from . import grbl
__all__ = [
    "grbl",
    "init_logging",
]

def init_logging(filter: typing.Optional[builtins.str] = None, path: typing.Optional[builtins.str] = None) -> None:
    r"""
    Initialize the Rust-side logger (`log` crate) so session
    diagnostics reach stderr or, when *path* is given, a dedicated
    log file (opened in append mode).  The filter defaults to
    ``warn`` and can be overridden with an ``env_logger`` filter
    string argument or via ``RUST_LOG`` (which always wins).  Calling
    again re-targets output and replaces the filter.
    """

