# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
GRBL device drivers implemented in Rust.

The central type is GrblSession: it owns the connection lifecycle (handshake, status polling, reconnect), interactive commands, and job streaming with character-counting flow control, stall detection and deadlock recovery. Dialects remain data owned by Rayforge: resolved command templates are passed into the session.
"""

import builtins
import typing
from . import parser
from . import types
__all__ = [
    "GrblSession",
    "MockTransport",
    "parser",
    "types",
]

@typing.final
class GrblSession:
    r"""
    A GRBL device session: connection lifecycle, streaming and
    interactive commands, entirely in Rust.
    
    All async methods return asyncio futures; events are delivered to
    `event_callback(name, payload)` on the event loop thread.
    """
    @property
    def state(self) -> types.DeviceState:
        r"""
        Current snapshot of the device state.
        """
    @property
    def buffer_count(self) -> builtins.int: ...
    @property
    def rx_buffer_size(self) -> builtins.int: ...
    @property
    def pending_commands(self) -> builtins.list[builtins.str]:
        r"""
        Commands awaiting their 'ok' acknowledgement.
        """
    @property
    def job_running(self) -> builtins.bool: ...
    @property
    def resource_uri(self) -> typing.Optional[builtins.str]: ...
    def __new__(cls, config: typing.Optional[dict], dialect: typing.Optional[dict] = None, event_callback: typing.Optional[typing.Any] = None) -> GrblSession: ...
    @staticmethod
    def with_transport(transport: MockTransport, config: typing.Optional[dict] = None, dialect: typing.Optional[dict] = None, event_callback: typing.Optional[typing.Any] = None) -> GrblSession:
        r"""
        Build a session around a [`MockTransport`] (for tests).
        """
    def connect(self) -> typing.Any:
        r"""
        Open the connection and start the background tasks.
        """
    def disconnect(self) -> typing.Any:
        r"""
        Stop all background tasks and close the transport.
        """
    def execute_interactive_command(self, command: builtins.str) -> typing.Any:
        r"""
        Send a command and synchronously await its full response,
        blocking any other command from interleaving.
        """
    def execute_command(self, command: builtins.str) -> typing.Any:
        r"""
        Queue a command for asynchronous processing and await its
        response.
        """
    def run(self, gcode: builtins.str, op_line_map: typing.Optional[typing.Mapping[builtins.int, builtins.int]] = None, op_estimates: typing.Optional[typing.Sequence[builtins.float]] = None, progress_callback: typing.Optional[typing.Any] = None) -> typing.Any:
        r"""
        Stream a G-code program using the character-counting
        protocol.
        
        `op_line_map` maps G-code line indices to op indices for
        progress reporting; `op_estimates` holds per-op estimated
        durations (seconds) used to scale per-line stall timeouts.
        """
    def run_raw(self, machine_code: builtins.str) -> typing.Any:
        r"""
        Execute a raw G-code string; GRBL realtime commands (?, ~, !)
        are sent via the control path instead of the stream.
        """
    def set_hold(self, hold: builtins.bool = True) -> typing.Any:
        r"""
        Pause (feed hold) or resume the device.
        """
    def cancel(self, emergency: builtins.bool = False) -> typing.Any:
        r"""
        Abort the running job: soft reset, queue cleanup and safety
        shutdown.
        """
    def home(self, axes: typing.Optional[typing.Sequence[builtins.str]] = None, active_wcs: builtins.str = 'G54') -> typing.Any:
        r"""
        Home all axes (`axes` is None) or the named axes (e.g.
        `["X"]`), then re-activate the active WCS via the toggle
        workaround.
        """
    def move_to(self, speed: builtins.float, x: builtins.float, y: builtins.float) -> typing.Any:
        r"""
        Move to an absolute position (mm) at `speed` (mm/min).
        """
    def jog(self, speed: builtins.float, deltas: typing.Sequence[tuple[builtins.str, builtins.float]]) -> typing.Any:
        r"""
        Jog by relative deltas (mm) at `speed` (mm/min).
        """
    def select_tool(self, tool_number: builtins.int) -> typing.Any: ...
    def set_power(self, power: typing.Optional[builtins.float] = None) -> typing.Any:
        r"""
        Set laser power.  `power` is the absolute S value; `None`
        (or zero) turns the laser off.
        """
    def set_focus_power(self, power: typing.Optional[builtins.float] = None) -> typing.Any:
        r"""
        Set laser power for focus mode; `None` waits for pending jogs
        to finish and turns the laser off.
        """
    def read_settings(self) -> typing.Any:
        r"""
        Read `$$` into `(key, raw_value)` pairs.
        """
    def write_setting(self, key: builtins.str, value: builtins.str) -> typing.Any: ...
    def set_wcs_offset(self, wcs_slot: builtins.str, x: builtins.float, y: builtins.float, z: typing.Optional[builtins.float]) -> typing.Any: ...
    def read_wcs_offsets(self) -> typing.Any:
        r"""
        Read `$#` WCS offsets, converted to mm when the device
        reports inches.
        """
    def read_parser_state(self) -> typing.Any:
        r"""
        Read the `$G` parser state to determine the active WCS.
        """
    def run_probe_cycle(self, axis_letter: builtins.str, max_travel: builtins.float, feed_rate: builtins.float) -> typing.Any:
        r"""
        Run a probe cycle (G38.2); returns the trigger position in mm
        or None on failure.
        """
    def detect_unit_system(self) -> typing.Any:
        r"""
        Infer the device's unit system ("metric"/"imperial") from the
        `$13` setting.
        """
    def update_dialect(self, dialect: dict) -> None:
        r"""
        Swap the dialect command templates at runtime.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class MockTransport:
    r"""
    An in-memory byte transport for tests.
    
    Feed bytes to the session with `push()` (as if the device had
    sent them), inspect everything the session sent with `sent()`,
    and simulate link state with `set_connected()` /
    `set_write_error()`.
    """
    def __new__(cls) -> MockTransport: ...
    def push(self, data: typing.Sequence[builtins.int]) -> None:
        r"""
        Deliver bytes to the session as if the device sent them.
        """
    def sent(self) -> builtins.list[bytes]:
        r"""
        All bytes written to the device so far.
        """
    def take_new_sent(self) -> builtins.list[bytes]:
        r"""
        Writes recorded since the previous call (or the last
        `clear_sent`): a monotonic cursor, so clearing the log never
        skips or replays chunks.  This is what device emulators
        should consume.
        """
    def clear_sent(self) -> None:
        r"""
        Clear the recorded sent bytes.
        """
    def set_connected(self, connected: builtins.bool) -> None:
        r"""
        Simulate connect/disconnect of the physical link.
        """
    def set_write_error(self, message: typing.Optional[builtins.str] = None) -> None:
        r"""
        Fail subsequent writes with this message (and mark the link
        down), simulating an unplugged cable.
        """
    def __repr__(self) -> builtins.str: ...

